#!/bin/bash
# Script to pause/disable Sanity webhook
# Usage: ./scripts/pause-sanity-webhook.sh

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  Pause/Disable Sanity Deploy Webhook"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Recommended: Disable via Sanity Management UI (easiest):"
echo ""
echo "  1. Go to: https://www.sanity.io/manage"
echo "  2. Select your project: 'gentle-piercing-blog' (Project ID: nfwijj0y)"
echo "  3. Navigate to: API > Webhooks"
echo "  4. Find the webhook named: 'Trigger Vercel Rebuild'"
echo "  5. Click on it and either:"
echo "     - Toggle it OFF (to pause temporarily)"
echo "     - Delete it (to remove permanently)"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Alternative: Use CLI (requires login):"
echo ""
echo "  1. Run: npx sanity login"
echo "  2. Run: npx sanity hook list"
echo "  3. Note the webhook ID for 'Trigger Vercel Rebuild'"
echo "  4. Run: npx sanity hook delete <webhook-id>"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Once disabled, the webhook will NOT trigger Vercel rebuilds"
echo "when content is updated in Sanity Studio."
echo ""
echo "To re-enable later, run: ./scripts/setup-sanity-webhook.sh <VERCEL_DEPLOY_HOOK_URL>"
echo ""

